# Generated by Django 3.2.12 on 2022-02-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.IntegerField(blank=True, null=True)),
                ('nazwa_kupujacego', models.CharField(blank=True, max_length=255, null=True)),
                ('termin_platnosci', models.DateTimeField(blank=True, null=True)),
                ('czy_oplacono', models.BooleanField(default=False)),
            ],
        ),
    ]
